Fix bootstrap from source instructions
Pins `EmPy<4` to fix the error:

    ImportError: cannot import name 'OVERRIDE_OPT' from 'em'

This fixes the "Bootstrap from source" instructions, which is using this
file to install requirements.